service: dna-mutation-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: dev
  region: us-east-1
  memorySize: 2048
  logRetentionInDays: 1
  timeout: 60
  
package:
  exclude:
    - ".env"

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline